//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaderCore {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class LocalizedStrings : global::System.Configuration.ApplicationSettingsBase {
        
        private static LocalizedStrings defaultInstance = ((LocalizedStrings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LocalizedStrings())));
        
        public static LocalizedStrings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failed to compile {0}")]
        public string ShaderCompilerFailed {
            get {
                return ((string)(this["ShaderCompilerFailed"]));
            }
            set {
                this["ShaderCompilerFailed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0} successfully compiled:")]
        public string ShaderCompilerResult {
            get {
                return ((string)(this["ShaderCompilerResult"]));
            }
            set {
                this["ShaderCompilerResult"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failed to link shader:")]
        public string ShaderLinkerFailed {
            get {
                return ((string)(this["ShaderLinkerFailed"]));
            }
            set {
                this["ShaderLinkerFailed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shader compiled successfully:")]
        public string ShaderLinkerResult {
            get {
                return ((string)(this["ShaderLinkerResult"]));
            }
            set {
                this["ShaderLinkerResult"] = value;
            }
        }
    }
}
